apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-02-05T19:19:40Z"
  generation: 1
  labels:
    app: gcp-deployment
  name: gcp-deployment
  namespace: default
  resourceVersion: "94204"
  selfLink: /apis/apps/v1/namespaces/default/deployments/gcp-deployment
  uid: cf6d8ee7-ce86-4821-b4f2-77ff1695eab9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gcp-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gcp-deployment
    spec:
      containers:
        - image: gcr.io/bubbly-axiom-303914/spring-boot-example@sha256:9ba83132234a834d419c04fdba8650778700e54e798522b2874301dbfe4e599b
          imagePullPolicy: IfNotPresent
          name: spring-boot-example
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /very
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2021-02-05T19:19:42Z"
      lastUpdateTime: "2021-02-05T19:19:42Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-02-05T19:19:40Z"
      lastUpdateTime: "2021-02-05T19:19:42Z"
      message: ReplicaSet "gcp-deployment-7f8f58f77d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1